-- SSMS'te PrestoPlus üzerinde çalıştırılır. Veri değiştirmez.
-- Kontrol edilecek RS_MUSTERI_BILGILERI.ID değerini aşağıda değiştirin.
DECLARE @MB_ID INT;
SET @MB_ID = 1592;

SELECT T.MB_ID, T.MUSTERI_ID, T.BOLUM_ID, T.PERSONEL_ID,
       T.U_STOK_ID, S.STOK_KODU, U.U_STOK_ADI,
       T.A_STOK_ID, A.A_STOK_ADI, T.U_STOK_LIMIT
FROM D00013.RS_MOBIL_SIPARIS_URUN_TANIMLARI T
INNER JOIN D00013.RS_MUSTERI_BILGILERI MB ON MB.ID = T.MB_ID
INNER JOIN D00013.RS_URUNLER_UST U ON U.U_STOK_ID = T.U_STOK_ID
INNER JOIN D00013.STOK S ON S.STOK_ID = T.U_STOK_ID
LEFT JOIN D00013.RS_URUNLER_ALT A
    ON T.A_STOK_ID <> 0
   AND A.ID = T.A_STOK_ID
   AND A.U_STOK_ID = T.U_STOK_ID
WHERE T.MB_ID = @MB_ID
ORDER BY U.U_STOK_ADI, A.A_STOK_ADI, T.U_STOK_ID, T.A_STOK_ID;

-- Bozuk ilişki veya yinelenen atama varsa sonuç üretir.
SELECT T.ID, T.MB_ID, T.U_STOK_ID, T.A_STOK_ID, N'BOZUK İLİŞKİ' AS KONTROL
FROM D00013.RS_MOBIL_SIPARIS_URUN_TANIMLARI T
LEFT JOIN D00013.RS_MUSTERI_BILGILERI MB ON MB.ID = T.MB_ID
LEFT JOIN D00013.RS_URUNLER_UST U ON U.U_STOK_ID = T.U_STOK_ID
LEFT JOIN D00013.RS_URUNLER_ALT A
    ON T.A_STOK_ID <> 0 AND A.ID = T.A_STOK_ID AND A.U_STOK_ID = T.U_STOK_ID
WHERE MB.ID IS NULL
   OR U.U_STOK_ID IS NULL
   OR (T.A_STOK_ID <> 0 AND A.ID IS NULL)
   OR (MB.ID IS NOT NULL AND
      (T.MUSTERI_ID <> MB.MUSTERI_ID OR
       T.BOLUM_ID <> MB.BOLUM_ID OR
       T.PERSONEL_ID <> MB.PERSONEL_ID));

SELECT MB_ID, U_STOK_ID, A_STOK_ID, COUNT(*) AS TEKRAR_SAYISI
FROM D00013.RS_MOBIL_SIPARIS_URUN_TANIMLARI
GROUP BY MB_ID, U_STOK_ID, A_STOK_ID
HAVING COUNT(*) > 1;
